# Generated by Django 4.2.5 on 2023-11-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='name',
        ),
    ]
