# Generated by Django 4.2.5 on 2023-11-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_location_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
