# Generated by Django 4.2.7 on 2023-12-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_projects_alter_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to='core.project'),
        ),
    ]
