# Generated by Django 4.2.7 on 2023-12-05 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_post_delete_browseprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_model', models.IntegerField()),
                ('vocal', models.FileField(upload_to='vocal_files')),
                ('instru', models.FileField(upload_to='instru_files')),
                ('final', models.FileField(upload_to='final_files')),
                ('coverimg', models.ImageField(default='blank-profile-picture.png', upload_to='cover_images')),
                ('title', models.CharField(blank=True, max_length=35)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
