# Generated by Django 4.2.7 on 2023-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='final',
            field=models.FileField(blank=True, null=True, upload_to='final_files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instru',
            field=models.FileField(blank=True, null=True, upload_to='instru_files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vocal',
            field=models.FileField(blank=True, null=True, upload_to='vocal_files'),
        ),
    ]
