# Generated by Django 4.2.7 on 2023-12-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='projects1',
        ),
    ]
