# Generated by Django 4.2.7 on 2023-12-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_projects_profile_projects1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects1',
            field=models.ManyToManyField(null=True, related_name='user_projects', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(null=True, to='core.profile'),
        ),
    ]
