# Generated by Django 4.2.7 on 2023-12-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_projects1_alter_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects1',
            field=models.ManyToManyField(related_name='user_projects', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='core.profile'),
        ),
    ]
