# Generated by Django 4.2.7 on 2023-12-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_projects1_alter_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects1',
            new_name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
