# Generated by Django 4.2.7 on 2024-01-31 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_friend_profile_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='recieved',
            new_name='received',
        ),
    ]
