# Generated by Django 4.2.7 on 2023-12-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id_model',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
