# Generated by Django 4.2.7 on 2023-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_projects1_profile_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coverimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='cover_images'),
        ),
    ]
