# Generated by Django 4.2.7 on 2024-01-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_recieved_friend_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='received',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='sent',
            new_name='sender',
        ),
    ]
