# Generated by Django 4.2.7 on 2023-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_project_id_model_remove_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=35)),
                ('vocal', models.FileField(blank=True, null=True, upload_to='vocal_files')),
                ('instru', models.FileField(blank=True, null=True, upload_to='instru_files')),
                ('final', models.FileField(blank=True, null=True, upload_to='final_files')),
                ('coverimg', models.ImageField(default='blank-profile-picture.png', upload_to='cover_images')),
                ('listens', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='published',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.published'),
        ),
    ]
