# Generated by Django 4.2.7 on 2023-12-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_coverimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Published',
        ),
    ]
