# Generated by Django 4.2.5 on 2023-12-20 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_published_profile_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='published',
            name='instru',
        ),
        migrations.RemoveField(
            model_name='published',
            name='vocal',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='published',
            name='artists',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
