# Generated by Django 4.2.7 on 2024-02-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_received_friend_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
