# Generated by Django 4.2.7 on 2023-12-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_popupcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopupContent',
        ),
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.published'),
        ),
    ]
