# Generated by Django 4.2.7 on 2023-12-18 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_popupcontent_profile_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed4ab6b1-18cd-42d0-90b4-df44b933b716'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='new_project', max_length=35),
        ),
    ]
