# Generated by Django 4.2.7 on 2024-03-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_proj',
            field=models.ManyToManyField(blank=True, related_name='favorite_project', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coverimg',
            field=models.ImageField(default='blank-project.png', upload_to='cover_images'),
        ),
    ]
