# Generated by Django 4.2.7 on 2023-12-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_profile_public_alter_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='coverimg',
        ),
        migrations.RemoveField(
            model_name='project',
            name='final',
        ),
        migrations.RemoveField(
            model_name='project',
            name='instru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vocal',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
