# Generated by Django 4.2.7 on 2023-12-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_profile_projects_remove_profile_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ManyToManyField(to='core.profile'),
        ),
    ]
