# Generated by Django 4.2.7 on 2024-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_profile_friends_alter_profile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='/media/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
