# Generated by Django 4.2.7 on 2024-01-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
