# Generated by Django 4.2.7 on 2024-01-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_profile_pub_proj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pub_proj',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ManyToManyField(blank=True, to='core.profile'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mp3', models.FileField(upload_to='mp3_tracks/')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
