# Generated by Django 4.2.7 on 2024-01-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_profile_projects_remove_profile_pub_proj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
